<?php

namespace Wnx\SidecarBrowsershot;

use Spatie\Browsershot\Browsershot;
use Wnx\SidecarBrowsershot\Functions\BrowsershotFunction;

class BrowsershotLambda extends Browsershot
{
    protected function callBrowser(array $command)
    {
        $result = BrowsershotFunction::execute([
            'command' => $command,
        ])->throw();

        $this->cleanupTemporaryHtmlFile();

        return $result->body();
    }

    public function save(string $targetPath)
    {
        dd("TODO: Implement save()", $targetPath);

        return parent::save($targetPath); // TODO: Change the autogenerated stub
    }

    public function savePdf(string $targetPath)
    {
        dd("TODO: Implement savePdf()", $targetPath);
        parent::savePdf($targetPath); // TODO: Change the autogenerated stub
    }
}
