name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  update_release_draft:
    uses: stefanzweifel/reusable-workflows/.github/workflows/phpstan.yml@main
    with:
      php_version: '8.3'
